### ISSUE TITLE
Explorer Transaction Details broken on localhost

### ISSUE THREAD

**Issue by iamgenchi** [hirosystems/explorer#421]
**Describe the bug**
The explorer has 2 issues on localhost:

1. The transaction details page don't work. The interaction with smart contract do not work.

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/81058044/112770608-2321f980-9073-11eb-8594-aced294f9d01.png">

2. It keeps asking for mainnet vs testnet

<img width="549" alt="image" src="https://user-images.githubusercontent.com/81058044/112770619-33d26f80-9073-11eb-9a38-13adbebf2bc4.png">

**To Reproduce**
1. Setup [stacks-local-dev](https://github.com/blockstack/stacks-local-dev)
2. Make sure to have the explorer setup

```
  explorer:
    image: ${EXPLORER_IMAGE}
    container_name: ${EXPLORER_NAME}
    restart: unless-stopped
    cpus: ${EXPLORER_CPU}
    mem_reservation: ${EXPLORER_MEM}
    ports:
      - ${EXPLORER_PORT_LOCAL}:${EXPLORER_PORT}
    environment:
      - MOCKNET_API_SERVER=http://${API_NAME}.mocknet:3999
      - TESTNET_API_SERVER=http://${API_NAME}.mocknet:3999
      - API_SERVER=http://${API_NAME}.mocknet:3999
    networks:
      - mocknet
    depends_on:
      - api
```

3. Go ahead to http://localhost:3000
4. Change the network to http://localhost:3999

You will see, it keeps asking for tetsnet vs mainet.

You will also notice, you cannot view transaction details, nor interact with smart contracts.
